### ISSUE TITLE
Meow toggle buttons

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/apollos-give#33]
![screenshot 2015-07-10 17 49 17](https://cloud.githubusercontent.com/assets/816517/8629743/1f266f98-272c-11e5-80d1-a92d68c5d1e6.png)

**Comment by jbaxleyiii** [comment]
@johnthepink I can't find where it comes from but somewhere this is happening

![center](https://www.dropbox.com/s/e8y6jfh2k5tmojw/Screenshot%202015-07-11%2016.00.36.png?dl=0)

**Comment by johnthepink** [comment]
@jbaxleyiii yes, yes it is.

**Comment by jbaxleyiii** [comment]
fixed with a redeploy of junction themes 

![wut](http://media.giphy.com/media/R8JwwO32vhaVy/giphy.gif)
